zk:
  image: bobrik/zookeeper
  ports:
   - 2181:2181
  environment:
    ZK_CONFIG: tickTime=2000,initLimit=10,syncLimit=5,maxClientCnxns=128,forceSync=no,clientPort=2181
    ZK_ID: 1

master:
  image: mesosphere/mesos-master:0.22.0-1.0.ubuntu1404
  net: host
  environment:
    MESOS_ZK: zk://127.0.0.1:2181/mesos
    MESOS_HOSTNAME: 192.168.59.103
    MESOS_IP: 192.168.59.103
    MESOS_QUORUM: 1
    MESOS_CLUSTER: docker-compose
    MESOS_WORK_DIR: /var/lib/mesos

slave:
  image: mesosphere/mesos-slave:0.22.0-1.0.ubuntu1404
  entrypoint: mesos-slave # https://twitter.com/ibobrik/status/589362154735800320
  net: host
  pid: host
  environment:
    MESOS_MASTER: zk://127.0.0.1:2181/mesos
    MESOS_HOSTNAME: 192.168.59.103
    MESOS_IP: 192.168.59.103
    MESOS_CONTAINERIZERS: docker,mesos
  volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /usr/local/bin/docker:/usr/bin/docker
    - /var/run/docker.sock:/var/run/docker.sock

marathon:
  image: mesosphere/marathon:v0.8.1
  net: host
  environment:
    MARATHON_MASTER: zk://127.0.0.1:2181/mesos
    MARATHON_ZK: zk://127.0.0.1:2181/marathon
    MARATHON_HOSTNAME: 192.168.59.103
